# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

VAGRANTFILE_API_VERSION = "2"
def security_groups( env_var )
  s = ENV[ env_var ]
  if s.nil?
    # Return some default
    case env_var
      when "AWS_SECURITY_GROUPS" then ["default_vpc_web_vt_ssh"]
      else                            []
    end
  else
    s.split
  end
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # vagrant plugin install vagrant-env
  config.env.enable
  # https://blog.john-pfeiffer.com/using-vagrant-to-deploy-instances-on-aws/
  config.ssh.pty = true
  config.vm.synced_folder ".", "/vagrant", disabled: true
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  # Run the provision script as the vagrant user (not root)
  config.vm.provision "shell", path: "../provision_scripts/provision_solr_centos7.sh", privileged: false

  # Application server
  config.vm.define :solr do |solr|
    solr.vm.hostname = "solr"

    solr.vm.provider :virtualbox do |vb, override|
      vb.box = "centos/7"
      vb.memory = 3072
      vb.cpus = 2
      override.vm.network :forwarded_port, host: 3000, guest: 3000
    end

    solr.vm.provider :aws do |aws, override|
      keypair = "#{ENV['KEYPAIR_NAME']}"
      keypair_filename = "#{ENV['KEYPAIR_FILE']}"
      override.vm.box = "aws_dummy"
      override.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
      override.vm.box_check_update = false
      aws.access_key_id = ENV['AWS_ACCESS_KEY']
      aws.secret_access_key = ENV['AWS_SECRET_KEY']
      aws.keypair_name = keypair
      #aws.ami = "ami-df0607b5" # Ubuntu Trusty LTS
      #aws.ami = "ami-5aee2235"
      aws.ami = "ami-9bf712f4"
      #aws.region = "us-east-1"
      aws.region = "eu-central-1"
      #aws.instance_type = "t2.medium"
      aws.instance_type = "t2.micro"
      # added start
      aws.subnet_id = ENV['AWS_SUBNET']
      # added end
      aws.security_groups = security_groups('AWS_SECURITY_GROUPS')
      override.ssh.username = "centos"
      override.ssh.private_key_path = "#{keypair_filename}"
      aws.tags = {
          'Name' => 'solr'
      }

    end

  end

end
